---
title: "STATS413 HW2"
author: ""
date: "Due September 21st, 2026 8:30am"
output: pdf_document
editor_options: 
  markdown: 
    wrap: 72
---

Formatting comments:

  * Please submit your work as a single PDF file generated using R Markdown.
  Your PDF file should be broken down into normal-size pages, 
  not one extremely long page. 
  
  * You may write any of your solutions by hand, but include the handwritten
  work as images within the R Markdown document. Make sure any photos of your work
  are oriented correctly, not rotated. 
  
  * Please make sure your code does not run off the page. You should split your 
  comments or code across multiple lines so that it displays fully in the PDF.
  
  * Please include all your code in the submission, along with all outputs.

  * See Lab 1 for detailed instructions on how to use R Markdown and how to include images.
  
  * You must submit your work on Gradescope.


# Problem 1, a continuation of HW 1 Problem 2 (Through lecture 4)

Referring to the data from HW 1 Problem 2, and your solutions to that problem:		

a. Interpret the slope. Initially, do so first formally according to the formulation from class. Then, give an informal interpretation in terms of the average value of a square foot of livable area.										

b. Interpret the intercept. Initially, do so formally according to the formulation in class. Is there an informal interpretation of the intercept in the context of this problem that might be meaningful, despite the fact that it represents an extrapolation?

c. What fraction of variation in Assessment is accounted for by Livable Area through our regression model?  Report the relevant quantity from the `R` output. Finally, what fraction of variation is accounted for by other factors besides livable area, such as differences in lot size, condition and quality of the building, and viability of the area? 

d. Point prediction: Based on the fitted equation, what can you say about the predicted price for a residence with 2,500 square feet of livable area? Use `R` to calculate this and show your code.

e. Predict the difference in assessed value for two residences where one residence is 200 square feet larger than the other. If you cannot complete your calculation with the information provided, explain why not.
    
# Problem 2 (Through lecture 4)

Assume that the following linear model holds: \begin{align*}
y = X\beta + \varepsilon,\;\;\; E(\varepsilon) = 0,\;\;\; Var(\varepsilon) =  \sigma^2_{\varepsilon} I,
\end{align*} where $X \in \mathbb{R}^{n\times (p+1)}$ is a design matrix
containing ones in the first column and $p$ predictor variables in the
remaining columns, $I$ is the identity matrix, and $n> p+1$. In lecture,
we suggested the following estimator for $\sigma^2_{\varepsilon}$:
\begin{align*}
\hat{\sigma}^2_\varepsilon &= \frac{1}{n-p-1}\sum_{i=1}^n(y_i-\hat{y}_i)^2,
\end{align*} where $\hat{y} = X\hat{\beta} = Hy$,
$\hat{\beta} = (X^TX)^{-1}X^Ty$, and $H=X(X^TX)^{-1}X^T$ as usual.

In this problem, we will show that $\hat{\sigma}^2_\varepsilon$ is an
unbiased estimator for $\sigma^2_{\varepsilon}$. To do so, we will use
the following result about \textit{quadratic forms} of random variables
(you may use it without proof). If $z \in \mathbb{R}^n$ is a vector of
random variables with $E(z) = \mu$, $\text{Var}(z) = \Sigma$, and
$A \in \mathbb{R}^{n\times n}$ is a constant (non-random)
$n$-dimensional symmetric matrix, then \begin{align*}
E(z^TAz) &= \mu^TA\mu + \text{tr}(A\Sigma),
\end{align*} where $\text{tr}(\cdot)$ denotes the trace of a square
matrix (the sum of its diagonal elements). For instance,
$tr(A) = \sum_{i=1}^n a_{ii}$, where $a_{ii}$ is the $i$th diagonal
entry of $A$.

a.  Argue that $\sum_{i=1}^n(y_i-\hat{y}_i)^2$ may be written as
    $y^T(I-H)y$.
    
b.  Show that $E(y)^T(I-H)E(y) = 0$.

c.  Show that
    $\text{tr}\{(I-H)\text{Var}(y)\} = \text{tr}\{\text{Var}(y)-H\text{Var}(y)\}  =\sigma^2_\varepsilon(n-p-1)$.

    Hint: the following two results about the trace of a matrix could
    come in handy. Let $A,B \in \mathbb{R}^{n\times n}$, let
    $C,D \in \mathbb{R}^{n\times m}$. Then: \begin{align*}
       \text{tr}(A+B) &= \text{tr}(A)+\text{tr}(B);\\
       \text{tr}(CD^T) &= \text{tr}(D^TC).
     \end{align*}

d.  Use these results to show that
    $E(\hat{\sigma}^2_{\varepsilon}) = \sigma^2_\varepsilon$, i.e. that
    $\hat{\sigma}^2_\varepsilon$ is an unbiased estimator of
    $\sigma^2_\varepsilon$.

e.  Does your finding in d) imply that
    $E(\hat{\sigma}_\varepsilon) = \sigma_\varepsilon$? Why or why not?

f.  Let $Z_1,...,Z_n$ be $iid$ random variables with
    $E(Z_i) = \theta$ and $Var(Z_i) = \sigma^2$. Show that the sample
    variance, $\hat{\sigma}^2$, is an unbiased estimator of $\sigma^2$,
    where \begin{align*}
    \hat{\sigma}^2 = \frac{1}{n-1}\sum_{i=1}^n(Z_i-\bar{Z})^2.
    \end{align*}

    Hint: try to apply the general result you proved about
    $\hat{\sigma}^2_\varepsilon$ in parts a-d.
